[package]
name = "derive_utils"
version = "0.8.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/derive_utils"
documentation = "https://docs.rs/derive_utils/"
readme = "README.md"
keywords = ["enum", "macros", "derive"]
categories = ["rust-patterns", "development-tools::procedural-macro-helpers"]
description = """
A procedural macro helper for easily writing custom derives for enums.
"""

[workspace]
members = ["examples/example", "examples/example_derive"]

[dependencies]
proc-macro2 = "0.4.13"
quote = "0.6.8"
syn = { version = "0.15.22", features = ["full"] }
