[package]
name = "example_derive"
version = "0.0.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
publish = false

[lib]
proc-macro = true

[dependencies]
derive_utils = { path = "../.." }
proc-macro2 = "0.4"
syn = "0.15"
